# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Install dependencies and package
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install .
      # Step 3: run tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python tests/test_superimposition.py
            python tests/test_data_downloader.py